# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-22 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdb',
            name='user_level',
        ),
    ]
